version: '3'
name: ai-playground-open-webui

services:
  ollama:
    image: ollama/ollama:latest
    container_name: '${COMPOSE_PROJECT_NAME}_ollama'
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: '${COMPOSE_PROJECT_NAME}_open-webui'
    environment:
      - WEBUI_AUTH=False
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://ollama:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
    volumes:
      - open-webui:/app/backend/data
      - ./docs:/app/backend/data/docs
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    depends_on:
      - ollama


volumes:
  ollama:
    name: ollama

  open-webui:
    name: open-webui
