version: '3'
name: ai-playground-rag

services:
  ollama: 
    image: ollama/ollama:latest
    container_name: '${COMPOSE_PROJECT_NAME}_ollama'
    volumes:
      - ollama:/root/.ollama
    networks:
      - net
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  chroma:
    image: chromadb/chroma:latest
    container_name: '${COMPOSE_PROJECT_NAME}_chroma'
    volumes:
      - chroma:/chroma/chroma
    networks:
      - net
    ports:
      - 8000:8000

  app:
    build: ./app
    container_name: '${COMPOSE_PROJECT_NAME}_app'
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://ollama:11434}
      - CHROMA_HOST=${CHROMA_HOST-chroma}
      - CHROMA_PORT=${CHROMA_PORT-8000}
      - FASTEMBED_CACHE_PATH=/fastembed_cache
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2-false}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - OPENAI_ENABLED=${OPENAI_ENABLED-false}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
      - ATLASSIAN_ENABLED=${ATLASSIAN_ENABLED-false}
      - ATLASSIAN_URL=${ATLASSIAN_URL}
      - ATLASSIAN_USERNAME=${ATLASSIAN_USERNAME}
      - ATLASSIAN_API_KEY=${ATLASSIAN_API_KEY}
      - AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
    depends_on:
      - ollama
      - chroma
    volumes:
      - fastembed_cache:/fastembed_cache
    networks:
      - net
    ports:
      - 8501:8501

volumes:
  ollama:
    name: ollama

  chroma:
    name: '${COMPOSE_PROJECT_NAME}_chroma'

  fastembed_cache:
    name: '${COMPOSE_PROJECT_NAME}_fastembed_cache'

networks:
  net:
